//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mrirac
{
    [Serializable]
    public class StartPickAndPlaceResponse : Message
    {
        public const string k_RosMessageName = "mrirac_msgs/StartPickAndPlace";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public StartPickAndPlaceResponse()
        {
            this.success = false;
        }

        public StartPickAndPlaceResponse(bool success)
        {
            this.success = success;
        }

        public static StartPickAndPlaceResponse Deserialize(MessageDeserializer deserializer) => new StartPickAndPlaceResponse(deserializer);

        private StartPickAndPlaceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "StartPickAndPlaceResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
