//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mrirac
{
    [Serializable]
    public class PickPlanResponse : Message
    {
        public const string k_RosMessageName = "mrirac_msgs/PickPlan";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public Trajectory.JointTrajectoryMsg trajectory;

        public PickPlanResponse()
        {
            this.success = false;
            this.trajectory = new Trajectory.JointTrajectoryMsg();
        }

        public PickPlanResponse(bool success, Trajectory.JointTrajectoryMsg trajectory)
        {
            this.success = success;
            this.trajectory = trajectory;
        }

        public static PickPlanResponse Deserialize(MessageDeserializer deserializer) => new PickPlanResponse(deserializer);

        private PickPlanResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            this.trajectory = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "PickPlanResponse: " +
            "\nsuccess: " + success.ToString() +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
