//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mrirac
{
    [Serializable]
    public class PickPlanRequest : Message
    {
        public const string k_RosMessageName = "mrirac_msgs/PickPlan";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pre_grasp_pose;
        public Geometry.PoseMsg grasp_pose;

        public PickPlanRequest()
        {
            this.pre_grasp_pose = new Geometry.PoseMsg();
            this.grasp_pose = new Geometry.PoseMsg();
        }

        public PickPlanRequest(Geometry.PoseMsg pre_grasp_pose, Geometry.PoseMsg grasp_pose)
        {
            this.pre_grasp_pose = pre_grasp_pose;
            this.grasp_pose = grasp_pose;
        }

        public static PickPlanRequest Deserialize(MessageDeserializer deserializer) => new PickPlanRequest(deserializer);

        private PickPlanRequest(MessageDeserializer deserializer)
        {
            this.pre_grasp_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.grasp_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pre_grasp_pose);
            serializer.Write(this.grasp_pose);
        }

        public override string ToString()
        {
            return "PickPlanRequest: " +
            "\npre_grasp_pose: " + pre_grasp_pose.ToString() +
            "\ngrasp_pose: " + grasp_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
