//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mrirac
{
    [Serializable]
    public class JointsAndTargetMsg : Message
    {
        public const string k_RosMessageName = "mrirac_msgs/JointsAndTarget";
        public override string RosMessageName => k_RosMessageName;

        public double[] current_joints;
        public Geometry.PoseMsg target_pose;

        public JointsAndTargetMsg()
        {
            this.current_joints = new double[6];
            this.target_pose = new Geometry.PoseMsg();
        }

        public JointsAndTargetMsg(double[] current_joints, Geometry.PoseMsg target_pose)
        {
            this.current_joints = current_joints;
            this.target_pose = target_pose;
        }

        public static JointsAndTargetMsg Deserialize(MessageDeserializer deserializer) => new JointsAndTargetMsg(deserializer);

        private JointsAndTargetMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_joints, sizeof(double), 6);
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_joints);
            serializer.Write(this.target_pose);
        }

        public override string ToString()
        {
            return "JointsAndTargetMsg: " +
            "\ncurrent_joints: " + System.String.Join(", ", current_joints.ToList()) +
            "\ntarget_pose: " + target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
