//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mrirac
{
    [Serializable]
    public class MeshObstaclesMsg : Message
    {
        public const string k_RosMessageName = "mrirac_msgs/MeshObstacles";
        public override string RosMessageName => k_RosMessageName;

        public MeshObstacleMsg[] mesh_obstacles;

        public MeshObstaclesMsg()
        {
            this.mesh_obstacles = new MeshObstacleMsg[0];
        }

        public MeshObstaclesMsg(MeshObstacleMsg[] mesh_obstacles)
        {
            this.mesh_obstacles = mesh_obstacles;
        }

        public static MeshObstaclesMsg Deserialize(MessageDeserializer deserializer) => new MeshObstaclesMsg(deserializer);

        private MeshObstaclesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mesh_obstacles, MeshObstacleMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.mesh_obstacles);
            serializer.Write(this.mesh_obstacles);
        }

        public override string ToString()
        {
            return "MeshObstaclesMsg: " +
            "\nmesh_obstacles: " + System.String.Join(", ", mesh_obstacles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
