//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mrirac
{
    [Serializable]
    public class MeshObstacleMsg : Message
    {
        public const string k_RosMessageName = "mrirac_msgs/MeshObstacle";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string action;
        public Shape.MeshMsg mesh;
        public Geometry.PoseMsg mesh_pose;

        public MeshObstacleMsg()
        {
            this.name = "";
            this.action = "";
            this.mesh = new Shape.MeshMsg();
            this.mesh_pose = new Geometry.PoseMsg();
        }

        public MeshObstacleMsg(string name, string action, Shape.MeshMsg mesh, Geometry.PoseMsg mesh_pose)
        {
            this.name = name;
            this.action = action;
            this.mesh = mesh;
            this.mesh_pose = mesh_pose;
        }

        public static MeshObstacleMsg Deserialize(MessageDeserializer deserializer) => new MeshObstacleMsg(deserializer);

        private MeshObstacleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.action);
            this.mesh = Shape.MeshMsg.Deserialize(deserializer);
            this.mesh_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.action);
            serializer.Write(this.mesh);
            serializer.Write(this.mesh_pose);
        }

        public override string ToString()
        {
            return "MeshObstacleMsg: " +
            "\nname: " + name.ToString() +
            "\naction: " + action.ToString() +
            "\nmesh: " + mesh.ToString() +
            "\nmesh_pose: " + mesh_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
