//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mrirac
{
    [Serializable]
    public class PickAndPlaceFeedbackMsg : Message
    {
        public const string k_RosMessageName = "mrirac_msgs/PickAndPlaceFeedback";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        // feedback
        public Trajectory.JointTrajectoryMsg trajectory;

        public PickAndPlaceFeedbackMsg()
        {
            this.trajectory = new Trajectory.JointTrajectoryMsg();
        }

        public PickAndPlaceFeedbackMsg(Trajectory.JointTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static PickAndPlaceFeedbackMsg Deserialize(MessageDeserializer deserializer) => new PickAndPlaceFeedbackMsg(deserializer);

        private PickAndPlaceFeedbackMsg(MessageDeserializer deserializer)
        {
            this.trajectory = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "PickAndPlaceFeedbackMsg: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
