//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MriracRelay
{
    [Serializable]
    public class pose_commandResponse : Message
    {
        public const string k_RosMessageName = "mrirac_relay/pose_command";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public pose_commandResponse()
        {
            this.success = false;
        }

        public pose_commandResponse(bool success)
        {
            this.success = success;
        }

        public static pose_commandResponse Deserialize(MessageDeserializer deserializer) => new pose_commandResponse(deserializer);

        private pose_commandResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "pose_commandResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
