//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MriracRelay
{
    [Serializable]
    public class pose_commandRequest : Message
    {
        public const string k_RosMessageName = "mrirac_relay/pose_command";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose;

        public pose_commandRequest()
        {
            this.pose = new Geometry.PoseMsg();
        }

        public pose_commandRequest(Geometry.PoseMsg pose)
        {
            this.pose = pose;
        }

        public static pose_commandRequest Deserialize(MessageDeserializer deserializer) => new pose_commandRequest(deserializer);

        private pose_commandRequest(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "pose_commandRequest: " +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
