#goal definition
geometry_msgs/Pose pre_grasp_pose
geometry_msgs/Pose grasp_pose
geometry_msgs/Pose pre_place_pose
geometry_msgs/Pose place_pose
---
#result definition
bool success
---
#feedback
trajectory_msgs/JointTrajectory trajectory